name:                subject
version:             0.1.0.0
github:              karamellpelle/subject
license:             GPL-3
license-file:        LICENSE
author:              karamellpelle@hotmail.com
maintainer:          karamellpelle@hotmail.com
copyright:           karamellpelle@hotmail.com

# FIXME: Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/karamellpelle/subject#readme>

extra-source-files:
- README.md
- CHANGELOG.md
data-dir:            data-dir
data-files:
- subject/**/*


dependencies:
- base
- relude
- attoparsec
- HsYAML
- data-default
#- libssh2
#- hashable
#- random
#mixin: <only use specified modules from package>

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wprepositive-qualified-module
- -Wno-name-shadowing

default-extensions:
 - NoImplicitPrelude
 - OverloadedStrings
 - ImportQualifiedPost
 - TypeApplications

# private libraries (https://github.com/sol/hpack#library-fields)
internal-libraries:
  subject-internal:
      source-dirs: source-lib
      # https://github.com/sol/hpack#handling-of-paths_-modules 
      when:
      - condition: false
        other-modules: Paths_subject 

executables:
  subject:
    main:                Main.hs
    source-dirs:         source-app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - subject-internal
    - optparse-applicative
    - directory
    - filepath
    - gitrev

tests:
  subject-test:
    main:                Spec.hs
    source-dirs:         test/subject-test
    # other-modules: <pull indidual files from project root>
    dependencies:
    - subject-internal
    - tasty
    - tasty-hunit
    - tasty-smallcheck
    - smallcheck
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
