name:                subject
version:             0.1.0.0
github:              karamellpelle/subject
license:             GPL-3
author:              karamellpelle@hotmail.com
maintainer:          karamellpelle@hotmail.com
copyright:           karamellpelle@hotmail.com
extra-source-files:
- README.md
- CHANGELOG.md
data-dir:            data-dir
data-files:
- subject/**/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/karamellpelle/subject#readme>

dependencies:
- base
- relude
- attoparsec
- HsYAML
- data-default
#- libssh2
#- hashable
#- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wprepositive-qualified-module

default-extensions:
 - NoImplicitPrelude
 - OverloadedStrings
 - ImportQualifiedPost
 - TypeApplications

library:
  source-dirs: source-lib
  when:
  - condition: false
    other-modules: Paths_subject # https://github.com/sol/hpack#handling-of-paths_-modules 

executables:
  subject:
    main:                Main.hs
    source-dirs:         source-app
    other-modules:       Paths_subject
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - subject
    - optparse-applicative
    - directory
    - filepath
    - gitrev

tests:
  subject-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - subject
    - tasty
    - tasty-hunit
    - tasty-smallcheck
    - smallcheck
